/**
 * Hata kodları (BACKEND_SPEC §3.6).
 *
 * Bu `code` alanı mobil tarafta doğrudan i18n anahtarı olarak kullanılır.
 * Backend kullanıcıya gösterilecek metin ÜRETMEZ — sadece bu enum'dan bir anahtar döner.
 * `message` yalnızca geliştirici içindir, mobilde gösterilmez.
 *
 * Kural: bir kod yayımlandıktan sonra yeniden adlandırılmaz (mobil sürümleri kırılır).
 */
export const ErrorCode = {
  // --- Genel ---
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INVALID_CURSOR: 'INVALID_CURSOR',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  APP_VERSION_UNSUPPORTED: 'APP_VERSION_UNSUPPORTED',

  // --- Kimlik / oturum (Faz 1) ---
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  IDENTITY_PROVIDER_REJECTED: 'IDENTITY_PROVIDER_REJECTED',
  ACCOUNT_DELETION_IN_PROGRESS: 'ACCOUNT_DELETION_IN_PROGRESS',

  // --- Abonelik (Faz 2) ---
  PREMIUM_REQUIRED: 'PREMIUM_REQUIRED',
  SUBSCRIPTION_SYNC_FAILED: 'SUBSCRIPTION_SYNC_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // --- Medya (Faz 3) ---
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  UPLOAD_ALREADY_COMPLETED: 'UPLOAD_ALREADY_COMPLETED',
  UPLOAD_OBJECT_MISSING: 'UPLOAD_OBJECT_MISSING',
  UPLOAD_CONTENT_TYPE_UNSUPPORTED: 'UPLOAD_CONTENT_TYPE_UNSUPPORTED',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_BATCH_TOO_LARGE: 'UPLOAD_BATCH_TOO_LARGE',

  // --- Gardırop (Faz 3) ---
  WARDROBE_ITEM_NOT_FOUND: 'WARDROBE_ITEM_NOT_FOUND',
  WARDROBE_ITEM_NOT_READY: 'WARDROBE_ITEM_NOT_READY',

  // --- Yapay zekâ (Faz 4) ---
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',
  AI_TAGGING_FAILED: 'AI_TAGGING_FAILED',

  // --- Kombinler (Faz 5) ---
  OUTFIT_NOT_FOUND: 'OUTFIT_NOT_FOUND',
  OUTFIT_SLOTS_INVALID: 'OUTFIT_SLOTS_INVALID',
  WEATHER_UNAVAILABLE: 'WEATHER_UNAVAILABLE',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',

  // --- Keşif (Faz 6) ---
  DISCOVERY_CARD_NOT_FOUND: 'DISCOVERY_CARD_NOT_FOUND',
  QUIZ_SET_NOT_FOUND: 'QUIZ_SET_NOT_FOUND',
  QUIZ_NOT_ENOUGH_SWIPES: 'QUIZ_NOT_ENOUGH_SWIPES',

  // --- Wishlist / temizlik (Faz 7) ---
  WISHLIST_ITEM_NOT_FOUND: 'WISHLIST_ITEM_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  LINK_PREVIEW_FAILED: 'LINK_PREVIEW_FAILED',
  LINK_NOT_ALLOWED: 'LINK_NOT_ALLOWED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ALL_ERROR_CODES = Object.values(ErrorCode) as ErrorCode[];
